#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# Add zuul user and group.  Note we don't want to rely on
# "useradd"'s group adding behaviour, because it might differ across
# distros.
groupadd zuul
useradd -m zuul -g zuul -s /bin/bash

cat > /etc/sudoers.d/zuul << EOF
zuul ALL=(ALL) NOPASSWD:ALL
EOF

chmod 0440 /etc/sudoers.d/zuul
visudo -c || die "Error setting zuul sudo!"

## Create zuul user public key file manually - CK
echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCtMZ9PTfg+o2XXc0Ui8tUowDe7+p1KKFP35Wbb36Xe3HsNF8jK0+hri0KFNmEGIGvSpSjNszyH4s5DPKnEtFjE78+W5MAJ8U4Ed3k6+UFZtrbAbUAhMausp5DmgYmeRZ3O7dieGbsK9QkUs/jIt0ZxKJCyDqhrZjJs/lrWV1ZI7sAAx0tE/PTzTPYNMZWSx1cz8NoOZan3ZQu944Z8B+OBp3tIw62fG3iH1OtnF195xNFgUjS0lvMK3fSYscvLfkmwZMHmJCSseJHKHkkKXWqjQlBpteG7M5GKv1m2yMVvzqYgughVKgsM5rHX/ScFg0aR1W5opBDWI5ezR1fEp47X" > /tmp/zuul-user-ssh-public-key

## ORIGINAL UPSTREAM COMMIT - CK
### this was copied from outside the chroot by extras.d
##_pub_key=/tmp/in_target.d/zuul-user-ssh-public-key

_pub_key=/tmp/zuul-user-ssh-public-key

if [ ! -f $_pub_key ]; then
    die "Can not find Zuul public key!"
fi

mkdir /home/zuul/.ssh
chmod 700 /home/zuul/.ssh
cp $_pub_key /home/zuul/.ssh/authorized_keys
chmod 644 /home/zuul/.ssh/authorized_keys

# cleanup everything to the right owner
chown -R zuul:zuul /home/zuul
